services:
  db:
    image: bitnami/postgresql:latest
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=queue-db
    ports:
      - "5433:5432"
